export enum EpubCfiParserErrorType {
    INVALID_RANGE_PATH = 'INVALID_RANGE_PATH',
    INCOMPATIBLE_OFFSET_TYPE = 'INCOMPATIBLE_OFFSET_TYPE',
    INVALID_CHARACTER_OFFSET = 'INVALID_CHARACTER_OFFSET',
    INVALID_ASSERTION = 'INVALID_ASSERTION',
    INVALID_EPUBCFI_START = 'INVALID_EPUBCFI_START',
    INVALID_EPUBCFI_END = 'INVALID_EPUBCFI_END',
    INVALID_PARAMETER = 'INVALID_PARAMETER',
    PATH_ENDS_WITH_INDIRECTION = 'PATH_ENDS_WITH_INDIRECTION',
    INVALID_SPATIAL_OFFSET = 'INVALID_SPATIAL_OFFSET',
    INVALID_SPATIAL_OFFSET_VALUE = 'INVALID_SPATIAL_OFFSET_VALUE',
    INVALID_STEP = 'INVALID_STEP',
    INVALID_INDIRECTION = 'INVALID_INDIRECTION',
    INVALID_TEMPORAL_OFFSET = 'INVALID_TEMPORAL_OFFSET',
    MISSING_END_RANGE = 'MISSING_END_RANGE',
    PATH_EMPTY = 'PATH_EMPTY'
}
