declare const styles: {
  readonly "main": string;
  readonly "primary": string;
  readonly "anchor_link": string;
  readonly "rotate180": string;
  readonly "fw_bold": string;
  readonly "text_right": string;
  readonly "mr_10": string;
  readonly "mt_10": string;
  readonly "main_navigation": string;
  readonly "active": string;
  readonly "nav_secondary": string;
  readonly "heading": string;
  readonly "keyboard_shortcuts_section": string;
  readonly "keyboard_shortcuts_button": string;
  readonly "keyboard_shortcuts_button_primary": string;
  readonly "keyboard_shortcuts_button_active": string;
  readonly "keyboard_shortcuts_menu": string;
  readonly "block_line": string;
  readonly "block_line_edit": string;
  readonly "no_list_style": string;
  readonly "button_primary": string;
  readonly "button_primary_small": string;
  readonly "readium2ElectronAnimation_TARGET": string;
  readonly "commonButton": string;
  readonly "button_transparency_icon": string;
  readonly "button_icon": string;
  readonly "button_refresh": string;
  readonly "button_icon_primary": string;
  readonly "button_keyboard": string;
  readonly "skip_link": string;
  readonly "outline": string;
  readonly "checkbox_keyboard": string;
  readonly "radio_list": string;
  readonly "breadcrumb": string;
};
export = styles;

