declare const styles: {
  readonly "___DEBUG___GLOBAL_CSS": string;
  readonly "align_items_center": string;
  readonly "anchor_link": string;
  readonly "breadcrumb": string;
  readonly "color_red": string;
  readonly "d_flex": string;
  readonly "d_none": string;
  readonly "flex_1": string;
  readonly "flex_none": string;
  readonly "flex_wrap": string;
  readonly "fw_bold": string;
  readonly "heading": string;
  readonly "heading_link": string;
  readonly "justify_content_between": string;
  readonly "m_0": string;
  readonly "main": string;
  readonly "mb_20": string;
  readonly "mb_30": string;
  readonly "mr_10": string;
  readonly "mt_10": string;
  readonly "mt_30": string;
  readonly "my_10": string;
  readonly "no_list_style": string;
  readonly "p_0": string;
  readonly "rotate180": string;
  readonly "text_center": string;
  readonly "text_right": string;
  readonly "visibility_hidden": string;
  readonly "visibility_visible": string;
  readonly "w_50": string;
};
export = styles;

