export declare const breadcrumb: string;
export declare const breadcrumb_container: string;
export declare const breadcrumb_icon: string;
export declare const button_transparency: string;
export declare const CSS_END_components_breadcrumbs: string;
export declare const CSS_START_components_breadcrumbs: string;
export declare const hide: string;
export declare const spaceLeft: string;
export declare const strongBreadcrumb: string;
