declare const styles: {
  readonly "___DEBUG___COMPONENTS_BUTTONS_CSS": string;
  readonly "block_line": string;
  readonly "button_catalog_infos": string;
  readonly "button_icon": string;
  readonly "button_keyboard": string;
  readonly "button_link": string;
  readonly "button_outline_accessibility": string;
  readonly "button_primary": string;
  readonly "button_primary_blue": string;
  readonly "button_primary_form_default": string;
  readonly "button_primary_icon": string;
  readonly "button_primary_small": string;
  readonly "button_refresh": string;
  readonly "button_secondary": string;
  readonly "button_secondary_blue": string;
  readonly "button_see_more": string;
  readonly "button_small": string;
  readonly "button_transparency": string;
  readonly "button_transparency_icon": string;
  readonly "button_transparency_icon_inactive": string;
  readonly "buttons_list": string;
  readonly "col_book_img": string;
  readonly "col_filter": string;
  readonly "disabled": string;
  readonly "heading": string;
  readonly "icon_end": string;
  readonly "skip_link": string;
};
export = styles;

