export declare const CSS_END_components_inputs: string;
export declare const CSS_START_components_inputs: string;
export declare const dropzone: string;
export declare const form_group: string;
export declare const form_group_catalog: string;
export declare const form_group_wrapper: string;
export declare const outline: string;
export declare const passphrase_error: string;
export declare const R2_CSS_CLASS__FORCE_NO_FOCUS_OUTLINE: string;
