export declare const ___DEBUG___COMPONENTS_INPUTS_CSS: string;
export declare const ___DEBUG___PARTIALS_MIXINS_CSS: string;
export declare const dropzone: string;
export declare const form_group: string;
export declare const form_group_catalog: string;
export declare const form_group_wrapper: string;
export declare const outline: string;
export declare const passphrase_error: string;
export declare const R2_CSS_CLASS__FORCE_NO_FOCUS_OUTLINE: string;
