export declare const button_transparency_icon: string;
export declare const display_options_item: string;
export declare const docked_header: string;
export declare const docked_header_controls: string;
export declare const modal_dialog_full: string;
export declare const modal_dialog_full_full: string;
export declare const modal_dialog_reader: string;
export declare const my_combobox_container: string;
export declare const popover_dialog_reader: string;
