declare const styles: {
  readonly "___DEBUG___COMPONENTS_PUBLICATIONS_CSS": string;
  readonly "author": string;
  readonly "block_book": string;
  readonly "block_book_list": string;
  readonly "book_author": string;
  readonly "book_title": string;
  readonly "box": string;
  readonly "cover": string;
  readonly "cover_img": string;
  readonly "icon_seemore": string;
  readonly "image_wrapper": string;
  readonly "infos_sup": string;
  readonly "legend": string;
  readonly "menu": string;
  readonly "no_img": string;
  readonly "no_img_wrapper": string;
  readonly "publication_description": string;
  readonly "publication_image_wrapper": string;
  readonly "publication_infos": string;
  readonly "publication_infos_wrapper": string;
  readonly "publication_list_infos": string;
  readonly "publication_list_title_authors": string;
  readonly "publication_list_wrapper": string;
  readonly "publication_title": string;
  readonly "publication_wrapper": string;
  readonly "title": string;
};
export = styles;

