
// create Dependency Injection Symbol Table
export const diSymbolTable = {
    "saga-middleware": Symbol("saga-middlewaire"),
    "store": Symbol("store"),
    // "win-registry": Symbol("win-registry"),
    "translator": Symbol("translator"),
    "downloader": Symbol("downloader"),
    "publication-repository": Symbol("publication-repository"),
    "opds-feed-repository": Symbol("opds-feed-repository"),
    "publication-view-converter": Symbol("publication-view-converter"),
//    "locator-view-converter": Symbol("locator-view-converter"),
    "opds-feed-view-converter": Symbol("opds-feed-view-converter"),
    "publication-storage": Symbol("publication-storage"),
    // "streamer": Symbol("streamer"),
    "device-id-manager": Symbol("device-id-manager"),
    "lcp-manager": Symbol("lcp-manager"),
    "lsd-manager": Symbol("lsd-manager"),
    "publication-service": Symbol("publication-service"),
    "opds-service": Symbol("opds-service"),
    "catalog-api": Symbol("catalog-api"),
    "publication-api": Symbol("publication-api"),
    "opds-api": Symbol("opds-api"),
    "apiapp-api": Symbol("apiapp-api"),
    "httpbrowser-api": Symbol("httpbrowser-api"),
    "keyboard-api": Symbol("keyboard-api"),
    "lcp-api": Symbol("lcp-api"),
    "session-api": Symbol("session-api"),
};
