export enum EpubCfiResolverErrorType {
    'XML_ID_ASSERTION_FAILED' = 'XML_ID_ASSERTION_FAILED',
    'STEP_VALUE_OUT_OF_BOUNDS' = 'STEP_VALUE_OUT_OF_BOUNDS',
    'INVALID_PATH_TYPE' = 'INVALID_PATH_TYPE',
}
