#!/bin/sh

# https://www.npmjs.com/package/npm-scripts-lifecycle
# https://app.unpkg.com/npm-scripts-lifecycle@1.0.0/files/package.json

npm cache clear --force
rm -rf node_modules/ && rm -f package-lock.json && sfw npm install --ignore-scripts --foreground-scripts --min-release-age=3 --allow-git=root && npm run build:prod

npm audit
npm outdated
(npm exec --no --offline -- taze --maturity-period 3 --fail-on-outdated --all --force --include-locked --concurrency 10 --loglevel debug --cwd . && npm exec --no --offline -- taze major --maturity-period 3 --fail-on-outdated --all --force --include-locked --concurrency 10 --loglevel debug --cwd .) || echo OK

# npm install --foreground-scripts
# TODO: preinstall, install and postinstall NPM lifecycle hooks for Electron, fsevents, ParcelWatcher, etc.?

cd node_modules/electron && DEBUG=@electron/get* force_no_cache=true node install.js && cd -
#cd node_modules/fsevents && DEBUG=@electron/get* force_no_cache=true node install.js && cd -

## INITIAL NPM CI (sets up local package cache):
# rm -rf node_modules/ &&\
set -xv ; container --version ; container system stop ; container system start ; container system status ; container stop test-container ; container rm --force test-container ; container prune ; container list --all ; container run --cpus 4 --memory 2g --platform linux/arm64 --name test-container --volume ${PWD}:/MOUNT -w /MOUNT registry.access.redhat.com/hi/nodejs:latest sh -c 'set -xv ; node --version ; npm --version ; echo $PATH ; env ; export NPM_CONFIG_PREFIX=/MOUNT/.flox/NPM_PREFIX ; export NPM_CONFIG_CACHE=/MOUNT/.flox/NPM_CACHE ; export NODE_PATH=/MOUNT/.flox/NPM_PREFIX/lib/node_modules ; npm install --global npm ; ls -als /usr/local/lib/node_modules || (ls -als /MOUNT/.flox/NPM_CACHE ; ls -als /MOUNT/.flox/NPM_PREFIX/bin ; ls -als /MOUNT/.flox/NPM_PREFIX/lib/node_modules) ; export PATH="/MOUNT/.flox/NPM_PREFIX/bin:/usr/local/bin:$PATH" ; echo $PATH ; echo $NODE_PATH ; npm --version ; npm config get cache ; npm config get prefix ; npm ci --ignore-scripts --foreground-scripts --min-release-age=3 --allow-git=root ; npm run build:prod' ; container list --all ; container stop test-container ; container rm --force test-container ; container prune ; container system status ; container system stop ; set +xv
## SUBSEQUENT FULL BUILD (more CPU cores and memory!):
set -xv ; container --version ; container system stop ; container system start ; container system status ; container stop test-container ; container rm --force test-container ; container prune ; container list --all ; container run --cpus 10 --memory 12g --platform linux/arm64 --name test-container --volume ${PWD}:/MOUNT -w /MOUNT registry.access.redhat.com/hi/nodejs:latest sh -c 'set -xv ; node --version ; npm --version ; echo $PATH ; env ; export NPM_CONFIG_PREFIX=/MOUNT/.flox/NPM_PREFIX ; export NPM_CONFIG_CACHE=/MOUNT/.flox/NPM_CACHE ; export NODE_PATH=/MOUNT/.flox/NPM_PREFIX/lib/node_modules ; ls -als /usr/local/lib/node_modules || (ls -als /MOUNT/.flox/NPM_CACHE ; ls -als /MOUNT/.flox/NPM_PREFIX/bin ; ls -als /MOUNT/.flox/NPM_PREFIX/lib/node_modules) ; export PATH="/MOUNT/.flox/NPM_PREFIX/bin:/usr/local/bin:$PATH" ; echo $PATH ; echo $NODE_PATH ; npm --version ; npm config get cache ; npm config get prefix ; npm run build:prod' ; container list --all ; container stop test-container ; container rm --force test-container ; container prune ; container system status ; container system stop ; set +xv
## SUBSEQUENT TYPESCRIPT GO (more CPU cores and memory!):
set -xv ; container --version ; container system stop ; container system start ; container system status ; container stop test-container ; container rm --force test-container ; container prune ; container list --all ; container run --cpus 10 --memory 12g --platform linux/arm64 --name test-container --volume ${PWD}:/MOUNT -w /MOUNT registry.access.redhat.com/hi/nodejs:latest sh -c 'set -xv ; node --version ; npm --version ; echo $PATH ; env ; export NPM_CONFIG_PREFIX=/MOUNT/.flox/NPM_PREFIX ; export NPM_CONFIG_CACHE=/MOUNT/.flox/NPM_CACHE ; export NODE_PATH=/MOUNT/.flox/NPM_PREFIX/lib/node_modules ; ls -als /usr/local/lib/node_modules || (ls -als /MOUNT/.flox/NPM_CACHE ; ls -als /MOUNT/.flox/NPM_PREFIX/bin ; ls -als /MOUNT/.flox/NPM_PREFIX/lib/node_modules) ; export PATH="/MOUNT/.flox/NPM_PREFIX/bin:/usr/local/bin:$PATH" ; echo $PATH ; echo $NODE_PATH ; npm --version ; npm config get cache ; npm config get prefix ; npm run typescript-check-GO' ; container list --all ; container stop test-container ; container rm --force test-container ; container prune ; container system status ; container system stop ; set +xv
## SUBSEQUENT TAZE (more CPU cores and memory!):
set -xv ; container --version ; container system stop ; container system start ; container system status ; container stop test-container ; container rm --force test-container ; container prune ; container list --all ; container run --cpus 10 --memory 12g --platform linux/arm64 --name test-container --volume ${PWD}:/MOUNT -w /MOUNT registry.access.redhat.com/hi/nodejs:latest sh -c 'set -xv ; node --version ; npm --version ; echo $PATH ; env ; export NPM_CONFIG_PREFIX=/MOUNT/.flox/NPM_PREFIX ; export NPM_CONFIG_CACHE=/MOUNT/.flox/NPM_CACHE ; export NODE_PATH=/MOUNT/.flox/NPM_PREFIX/lib/node_modules ; ls -als /usr/local/lib/node_modules || (ls -als /MOUNT/.flox/NPM_CACHE ; ls -als /MOUNT/.flox/NPM_PREFIX/bin ; ls -als /MOUNT/.flox/NPM_PREFIX/lib/node_modules) ; export PATH="/MOUNT/.flox/NPM_PREFIX/bin:/usr/local/bin:$PATH" ; echo $PATH ; echo $NODE_PATH ; npm --version ; npm config get cache ; npm config get prefix ; (npm exec --no --offline -- taze --maturity-period 3 --fail-on-outdated --all --force --include-locked --concurrency 10 --loglevel debug --cwd . && npm exec --no --offline -- taze major --maturity-period 3 --fail-on-outdated --all --force --include-locked --concurrency 10 --loglevel debug --cwd .) || echo OK' ; container list --all ; container stop test-container ; container rm --force test-container ; container prune ; container system status ; container system stop ; set +xv
